MAX_BODY_SIZE = 1024
DEFAULT_NOTIFIER_TIMEOUT = 10.0
HEALTH_SHUTDOWN_TIMEOUT = 2.0
LOG_FORMAT = "%(asctime)s | %(levelname)s | %(message)s"
DEFAULT_HEALTH_PORT = 8080
DEFAULT_HEALTH_HOST = "0.0.0.0"
DEFAULT_HEALTH_PATH = "/health"
DEFAULT_RESPONSE_CODE = 200
